### ISSUE TITLE
现在斐讯的盒子普遍没有任务列表，但是这个任务列表应该是安卓内置的，有办法呼出么？

### ISSUE THREAD

**Issue by ihipop** [jjm2473/PhicommLauncherr#1]
现在斐讯的盒子普遍没有任务列表，但是这个任务列表应该是安卓内置的，有办法呼出么？

**Comment by jjm2473** [comment]
不清楚哦，我只是替换几个应用而已，系统框架没怎么研究，因为全被dex2oat了，要分析的话就要先oat2dex，可能还要自己签名框架，不知道斐讯有没有校验自家签名的。

我搞这个盒子主要是给父母用的，能正常使用就好了，这周估计就会把盒子寄回家，也没时间再去研究了。

**Comment by ihipop** [comment]
我说的是Recent List，就是那个Recents Screen，标准的安卓是com.android.systemui里面的recent view
标准安卓是绑定到187这个按键码上的（AndroidKey.APP_SWITCH）
就是不知道怎么才能模拟，我现在手里3个N1，但是没按键模拟的app

**Comment by jjm2473** [comment]
`adb shell input keyevent HOME`
HOME 换成需要的按键，按键的表百度下就有了

**Comment by ihipop** [comment]
> adb shell input keyevent

好 谢谢 回去试下

**Comment by jjm2473** [comment]
话说你又搞上斐讯盒子了？

**Comment by ihipop** [comment]
Zidoo自用，N系列两方老人家留一台自己留1台。
垃圾佬的恶趣味。

**Comment by jjm2473** [comment]
哈哈，跟我一样，我买的是T1

**Comment by ihipop** [comment]
试过了 通过 
`adb shell input keyevent APP_SWITCH ` 就可以呼出这个切换列表

**Comment by jjm2473** [comment]
或许可以让语音键唤出任务列表

**Comment by ihipop** [comment]
> 或许可以让语音键唤出任务列表

是可以 去 /system/usr/keylayout 改个按键映射就好了
但是问题是我目前用的遥控器是yyf的，没有多余按键给我映射了。。其实是遥控器垃圾，长按不是另一个键码

**Comment by ihipop** [comment]
我想应该可以通过监听HOME长按来实现 两次间隔差异多少就呼出这个界面（但是要写程序。。。）

**Comment by jjm2473** [comment]
HOME键是系统框架处理了的, 应用好像没办法感知, 一般的安卓系统按HOME启动器会回到最上边或者最左边, 斐讯的只有自带的启动器才根据onNewIntent实现了, 长按HOME键更是没任何实现.
