### ISSUE TITLE
大佬有成品吗？菜鸟不会生成成品

### ISSUE THREAD

**Issue by MemoryCollection** [jjm2473/PhicommLauncherr#2]
我的是投影仪 想试试

**Comment by jjm2473** [comment]
只对斐讯有效，因为这个包名就是替换斐讯的，而且打包的时候需要使用相应的系统证书，斐讯使用的是testkey，可以自己签

**Comment by MemoryCollection** [comment]
哦哦哦 那不合适 我的不是斐讯



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liangbin ***@***.***&gt;; 
发送时间: 2024年2月18日(星期天) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jjm2473/PhicommLauncherr] 大佬有成品吗？菜鸟不会生成成品 (Issue #2)





 
只对斐讯有效，因为这个包名就是替换斐讯的，而且打包的时候需要使用相应的系统证书，斐讯使用的是testkey，可以自己签
